# Generated by Django 5.0.3 on 2024-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_passagem_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_confort',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_econ',
            field=models.CharField(max_length=30),
        ),
    ]
